let state = {
    days1: [
        {
            day: '17.05',
            position: false,
            WorkInDay: [],
        },
        {
            day: '18.05',
            position: false,
            WorkInDay: [],
        },
        {
            day: '19.05',
            position: false,
            WorkInDay: [],
        },
        {
            day: '20.05',
            position: false,
            WorkInDay: [],
        },
        {
            day: '21.05',
            position: false,
            WorkInDay: [],
        },
        {
            day: '22.05',
            position: false,
            WorkInDay: [],
        },
        {
            day: '23.05',
            position: false,
            WorkInDay: [],
        },
    ],
    days2: [
        {
            day: '10.05',
            position: false,
            WorkInDay: [],
        },
        {
            day: '11.05',
            position: false,
            WorkInDay: [],
        },
        {
            day: '12.05',
            position: false,
            WorkInDay: [],
        },
        {
            day: '13.05',
            position: false,
            WorkInDay: [],
        },
        {
            day: '14.05',
            position: false,
            WorkInDay: [],
        },
        {
            day: '15.05',
            position: false,
            WorkInDay: [],
        },
        {
            day: '16.05',
            position: false,
            WorkInDay: [],
        },
    ],
    foodData: {
        breakfast: false,
        lunch: false,
        dinner: false,
    },
    photoUser: '',
    allPosts: [],
    foodPersonal: [],
    weightControl: [],
    WorkAllDays: {
    },
    breakfastAllDays: {},
    lunchAllDays: {},
    dinnerAllDays: {},
    foodCalc: {
        '10.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '11.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '12.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '13.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '14.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '15.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '16.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '17.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '18.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '19.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '20.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '21.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '22.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        },
        '23.05': {
            allSquirrelsBreakfast: 0,
            allFatsBreakfast: 0,
            allCarbohydratesBreakfast:0,
            allCalloryBreakfast: 0,
            allSquirrelsLunch: 0,
            allFatsLunch: 0,
            allCarbohydratesLunch:0,
            allCalloryLunch: 0,
            allSquirrelsDinner: 0,
            allFatsDinner: 0,
            allCarbohydratesDinner:0,
            allCalloryDinner: 0,
        }
    }
}

export default state